"""Generate the shared public pages. Run with Python 3; no dependencies required."""
from pathlib import Path
import html, json, re

ROOT = Path(__file__).resolve().parents[1]
ORIGIN = 'https://www.marcuslefton.com'
NAV = [('advisory', 'Private Advisory', '/advisory/'), ('evidence', 'Evidence', '/evidence/'), ('publication', 'Mastery in Motion', '/mastery-in-motion/')]

def button(text='Work with Marcus', href='/advisory/', cls='button'):
    return f'<a class="{cls}" href="{href}">{text}</a>'

def page(path, title, description, content, active='', kind='', noindex=False):
    nav = ''.join(f'<a href="{url}"'+(' aria-current="page"' if key == active else '')+f'>{label}</a>' for key,label,url in NAV)
    canonical = ORIGIN + ('/' if path == 'index.html' else '/' + path.replace('index.html',''))
    schema = {'@context':'https://schema.org','@type':'WebPage','name':title,'url':canonical,'description':description,'isPartOf':{'@type':'WebSite','name':'Marcus Lefton | VYRTŪOSITI','url':ORIGIN}}
    if path == 'index.html':
        schema['about'] = {'@type':'Person','name':'Marcus Lefton','url':ORIGIN,'jobTitle':'Founder and Principal Consultant','worksFor':{'@type':'Organization','name':'VYRTŪOSITI'},'sameAs':['https://www.linkedin.com/in/marcuslefton/']}
    doc = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title><meta name="description" content="{html.escape(description, quote=True)}">
<link rel="canonical" href="{canonical}"><meta name="theme-color" content="#080909">
<meta property="og:type" content="website"><meta property="og:title" content="{html.escape(title, quote=True)}"><meta property="og:description" content="{html.escape(description, quote=True)}"><meta property="og:url" content="{canonical}">
<meta property="og:image" content="https://i.imgur.com/57TScBW_d.png?maxwidth=520&amp;shape=thumb&amp;fidelity=high">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg"><link rel="preload" href="/assets/manrope-400.woff" as="font" type="font/woff" crossorigin>
<link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/refinements.css"><script src="/assets/site.js" defer></script>
{'<meta name="robots" content="noindex,follow">' if noindex else ''}
<script type="application/ld+json">{json.dumps(schema, ensure_ascii=False)}</script></head>
<body class="{kind}"><a class="skip" href="#main">Skip to content</a>
<header class="site-header"><div class="wrap header-inner"><a class="wordmark" href="/" aria-label="Marcus Lefton — Home"><strong>Marcus Lefton</strong><span>VYRTŪOSITI</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="navigation">Menu<span aria-hidden="true">+</span></button><nav id="navigation" aria-label="Main navigation">{nav}{button(href='/advisory/#apply',cls='button button-small nav-cta')}</nav></div></header>
<main id="main">{content}</main>
<footer class="site-footer"><div class="wrap"><div class="footer-top"><a class="wordmark" href="/"><strong>Marcus Lefton</strong><span>VYRTŪOSITI</span></a><p>Performance architecture.<br>A clearer way to your next result.</p><div><a href="/contact/">Contact</a><a href="https://www.linkedin.com/in/marcuslefton/">LinkedIn</a><a href="/mastery-in-motion/">The Sunday letter</a></div></div><div class="footer-bottom"><span>© 2026 VYRTŪOSITI LLC</span><div><a href="/privacy/">Privacy</a><a href="/terms-of-service/">Terms</a></div></div></div></footer></body></html>'''
    dest = ROOT / path; dest.parent.mkdir(parents=True, exist_ok=True); dest.write_text(doc)

def newsletter_form(id='newsletter'):
    return f'''<form class="newsletter-form" id="{id}" action="/.netlify/functions/subscribe" method="post" data-form="newsletter">
<label for="{id}-email">Email address</label><div class="email-row"><input id="{id}-email" name="email" type="email" autocomplete="email" placeholder="Your email address" maxlength="254" required><button class="button" type="submit">Join the Sunday letter</button></div>
<div class="honeypot" aria-hidden="true"><label>Leave empty<input name="website" type="text" tabindex="-1" autocomplete="off"></label></div><input type="hidden" name="source" value="mastery_in_motion"><p class="form-status" role="status" aria-live="polite"></p><p class="form-note">Free. One useful email every Sunday. Unsubscribe anytime. <a href="/privacy/">Privacy</a></p></form>'''

def letter_strip():
    return '<section class="letter-strip" id="join"><div class="wrap letter-grid"><div><p class="eyebrow">The Sunday letter</p><h2>Mastery in Motion.</h2><p>Recognize the pattern behind an expensive problem. Take one useful idea into your next week.</p>'+button('Read a field note','/mastery-in-motion/the-cost-of-compensation/','text-link')+'</div>'+newsletter_form('home-letter')+'</div></section>'

logo_items = [('apple','Apple'),('tesla','Tesla'),('amazon','Amazon'),('microsoft','Microsoft'),('bainandcompany','Bain & Company'),('us-air-force','U.S. Air Force'),('mlb','MLB'),('ncaa','NCAA'),('flow-research-collective','Flow Research Collective — former coach and program leader')]
logo_marks = ''.join(f'<div class="logo-item logo-{file}"><img src="/assets/logos/{file}.{"png" if file == "flow-research-collective" else "svg"}" alt="{name}" width="150" height="62" loading="eager"></div>' for file,name in logo_items)
logos = '<section class="experience client-experience wrap" aria-labelledby="client-heading"><div class="client-heading"><p class="eyebrow" id="client-heading">Clients come from worlds where performance matters.</p><p>Selected client backgrounds across private advisory, professional sport, and programs delivered through FRC.</p></div><div class="logo-marquee"><input class="logo-pause" id="logo-pause" type="checkbox"><label class="logo-pause-label" for="logo-pause">Pause motion</label><div class="logo-window"><div class="logo-track"><div class="logo-group">'+logo_marks+'</div><div class="logo-group" aria-hidden="true">'+logo_marks+'</div></div></div></div></section>'

system = (ROOT / 'tools/diagnostic.html').read_text()
home=f'''<section class="hero wrap"><div class="hero-copy"><p class="eyebrow">Private performance advisory</p><h1>Find the constraint.<br><span>Change the result.</span></h1><p class="hero-lead">For founders and high-stakes operators who are delivering results at too high a personal cost.</p><p class="hero-support">I connect physiology, attention, judgment, and the way work gets done—to find where a change will make the greatest difference.</p><div class="actions">{button()}{button('See the evidence','/evidence/','text-link')}</div><p class="hero-detail">Private advisory with Marcus · $5,000 · 30 days</p></div><figure class="portrait"><img src="/assets/marcus-lefton.webp" alt="Marcus Lefton" width="840" height="1826" fetchpriority="high" decoding="async"><figcaption>Professional sport.<br>Applied performance.<br>Private advisory.</figcaption></figure></section>
<section class="home-evidence paper-section"><div class="wrap home-evidence-grid"><figure><blockquote>“The strongest testimonial I can give you is the five digit sum I pay to have six months of private advisory calls with Marcus. I feel like I am getting every penny’s worth.”</blockquote><figcaption><strong>Ethan Evans</strong><span>Former Amazon VP · Earlier six-month private advisory engagement</span></figcaption></figure><div class="home-case"><p class="eyebrow">Inside an earlier engagement</p><h2>His strongest Q1<br>in five years.</h2><p>We protected David’s best hours for higher-value work and built recovery into the working day.</p><p class="case-outcome">He reported nearly 200% of plan after three months.</p><p class="case-limits">David V. · Client-reported outcome from earlier work; not a prediction for the 30-day Intensive.</p>{button('Examine the case','/evidence/#case','text-link')}</div></div></section>{logos}{system}
<section class="offer-section wrap"><div><p class="eyebrow">The Performance Architecture Intensive</p><h2>One result.<br><span>Thirty days.</span></h2><p>I carry the analysis and intervention design. You bring the context, test the changes, and help determine what comes next.</p>{button('Explore the Intensive','/advisory/')}</div><div class="offer-spec"><p>Private. Direct. Built around you.</p><dl><div><dt>Focus</dt><dd>One consequential result</dd></div><div><dt>Duration</dt><dd>30 days</dd></div><div><dt>Investment</dt><dd>$5,000</dd></div><div><dt>Output</dt><dd>Your Performance Map<br>Tested changes. A next move.</dd></div></dl></div></section><section class="about-section wrap" id="marcus"><div class="section-intro"><p class="eyebrow">Why this perspective</p><h2>Different arenas.<br><span>One connected view.</span></h2><p>Professional baseball. Human-performance technology. Applied neuroscience. Private advisory. Each setting sharpened how I connect the person, the demands, and the result.</p></div><div class="arena-list"><div><h3>Colorado Rockies</h3><span>Physical performance</span><p>Readiness, physical demand, and recovery across a long season.</p></div><div class="research-arena"><h3>Performance research<br>&amp; technology</h3><div class="research-organizations"><p><strong>Sparta Science</strong><br>Physical performance, measurement, and technology. <a class="sparta-acquisition" href="https://ouraring.com/blog/oura-acquires-sparta-science-to-expand-enterprise-capabilities/">Acquired by ŌURA in 2024.</a></p><p><strong>Flow Research Collective</strong><br>Former coach and program leader. Applying flow science to attention, state, and performance.</p></div></div><div><h3>VYRTŪOSITI</h3><span>Private advisory</span><p>Working directly with the person whose decisions, energy, and execution shape the result.</p></div></div></section>
{letter_strip()}'''
page('index.html','Marcus Lefton | Performance Architecture & Private Advisory','Private advisory for founders and high-stakes operators delivering results at too high a personal cost. Work directly with Marcus Lefton in a $5,000, 30-day Intensive.',home,kind='home')

application='''<section class="application-section wrap" id="apply"><div class="application-intro"><p class="eyebrow">Work with Marcus</p><h2>Tell me what<br>needs to change.</h2><p>I’ll review your application and reply by email. If the fit looks promising, we’ll have a complimentary 15-minute conversation about the result, the working relationship, and the scope.</p><p class="muted">The Intensive is $5,000 for 30 days. Applying carries no payment obligation.</p><p class="small">Prefer email? <a class="text-link" href="mailto:marcus@marcuslefton.com">marcus@marcuslefton.com</a></p></div>
<form class="application-form" action="/.netlify/functions/apply" method="post" data-form="application"><div class="field-pair"><label>Your name<input name="first_name" autocomplete="name" maxlength="120" required></label><label>Email address<input type="email" name="email" autocomplete="email" maxlength="254" required></label></div><label>Role / company<input name="role_company" autocomplete="organization" maxlength="240" required></label><label>What result matters, and what is getting in the way?<textarea name="current_issue" rows="4" maxlength="3000" required placeholder="A few sentences is enough."></textarea></label><label>What have you already tried? <span class="optional">Optional</span><textarea name="already_tried" rows="2" maxlength="2000"></textarea></label><div class="field-pair"><label>Why is now the right time? <span class="optional">Optional</span><input name="why_now" maxlength="600"></label><label>LinkedIn / website <span class="optional">Optional</span><input type="url" name="linkedin_website" maxlength="500" placeholder="https://"></label></div><label>Are you open to a $5,000 engagement if there is a fit?<select name="readiness" required><option value="">Select an answer</option><option value="Yes">Yes</option><option value="Maybe, depends on fit">I’d like to understand the fit first</option><option value="Not right now">Not right now</option></select></label><div class="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabindex="-1" autocomplete="off"></label></div><input type="hidden" name="source" value="advisory"><button class="button" type="submit">Send your application</button><p class="form-status" role="status" aria-live="polite"></p><p class="form-note">Your details are used to respond to this enquiry. <a href="/privacy/">Privacy policy</a>.</p></form></section>'''
advisory=f'''<section class="page-hero wrap"><p class="eyebrow">Private advisory · VYRTŪOSITI</p><h1>One consequential result.<br><span>A system built<br class="mobile-break"> to support it.</span></h1><div class="page-hero-bottom"><p class="lead">A 30-Day Performance Architecture Intensive with Marcus Lefton. Find the constraint, test the intervention, and leave with a clearer way forward.</p><div class="offer-price"><strong>$5,000</strong><span>30 days · Private 1:1</span>{button('Work with Marcus','#apply')}</div></div></section>
<section class="wrap section-rule fit-section"><h2>You are still delivering.<br><span>The cost keeps rising.</span></h2><div><p>Important work waits until the evening. Decisions keep returning to you. Recovery happens around whatever is left. Your current approach asks more of you than the result should require.</p><p>The Intensive is for a founder or high-stakes operator with a specific result worth solving for—and enough willingness to change how it gets produced.</p></div></section>
<section class="paper-section"><div class="wrap"><div class="section-intro"><p class="eyebrow">The engagement</p><h2>We work on the thing<br>that changes the rest.</h2><p>I carry the analysis and intervention design. You bring the context and test the changes in your actual week.</p></div><ol class="process-list"><li><span>01</span><div><h3>Get the real picture.</h3><p>Define the result. Review relevant calendars, responsibilities, work patterns, and recovery context. Establish a baseline we can use.</p></div><small>Context & baseline</small></li><li><span>02</span><div><h3>Find the constraint.</h3><p>Look across capacity, cognition, capability, execution, leverage, and context. Separate the presenting problem from the most useful explanation to test.</p></div><small>Your Performance Map</small></li><li><span>03</span><div><h3>Change. Observe. Refine.</h3><p>Run a focused intervention, review what happens, and adjust. Record what to keep, what to stop, and the next priority.</p></div><small>Evidence & next moves</small></li></ol></div></section>
<section class="deliverables wrap"><div><p class="eyebrow">What you leave with</p><h2>A working system.<br><span>Yours to use.</span></h2><p>Your Performance Map brings the result, constraint, decisions, and evidence into one place.</p>{button('See an example','/evidence/#deliverable','text-link')}</div><dl class="deliverable-list"><div><dt>A clear result and baseline</dt><dd>What matters, where you are starting, and how progress will be judged.</dd></div><div><dt>A working constraint map</dt><dd>The strongest explanation, the evidence behind it, and what remains uncertain.</dd></div><div><dt>A focused intervention</dt><dd>Changes tested inside your work and life, with a record of what happened.</dd></div><div><dt>A practical next sequence</dt><dd>What to keep, what to stop, and what deserves attention next.</dd></div></dl></section>
<section class="quote-band wrap"><blockquote>“I feel like I am getting every penny’s worth.”</blockquote><p>Ethan Evans · Former Amazon VP · Earlier private advisory engagement</p></section>
<section class="faq-section wrap"><h2>A few practical questions.</h2><div class="faq-list"><details><summary>What does the 30-day commitment involve?</summary><p>You share the relevant context, take part in focused working conversations, and test agreed changes. We agree the meeting rhythm and scope before payment, around your schedule and the result.</p></details><details><summary>What is the difference between the fit call and the Intensive?</summary><p>The complimentary 15-minute conversation helps us decide whether to work together. The paid Intensive includes the deeper review, intervention design, testing, and Performance Map.</p></details><details><summary>Does every engagement cover all six dimensions?</summary><p>We examine the connections that matter to your result. The work may concentrate on a small number of changes once the evidence points to a useful place to intervene.</p></details><details><summary>What outcomes can you promise?</summary><p>A defined process and tangible working outputs. Business and personal outcomes depend on your context, implementation, and factors beyond the engagement. Earlier client results describe individual experiences.</p></details><details><summary>What happens after the 30 days?</summary><p>You leave with the working map, evidence, and next sequence. Any further advisory work is a separate conversation, with its scope and fee agreed in writing.</p></details></div></section>{application}'''
page('advisory/index.html','Private Advisory | 30-Day Performance Architecture Intensive','A $5,000, 30-day private engagement with Marcus Lefton. Define the result, find the constraint, test changes, and build your Performance Map.',advisory,'advisory')

evidence=f'''<section class="page-hero wrap"><p class="eyebrow">Evidence</p><h1>Look at the work.<br><span>Then judge the value.</span></h1><p class="lead">Selected client accounts and the thinking behind an engagement. Different starting points, different contexts, individual outcomes.</p></section>
<section class="paper-section" id="case"><article class="wrap case-study"><div class="case-top"><div><p class="eyebrow">Case study · Commercial performance</p><h2>His strongest Q1<br>in five years.</h2><p>David V. · Earlier engagement · Three-month account</p></div><div class="case-stat"><strong>~200<span>%</span></strong><span>of plan, reported by the client</span></div></div><blockquote class="case-quote">“Within three months, I had my best Q1 ever, hitting almost 200% of plan — the highest I’ve performed in five years.”</blockquote><div class="case-body"><div><h3>The problem to solve</h3><p>Make strong commercial performance more repeatable while improving the relationship between demanding work, recovery, and life at home.</p></div><div><h3>What I looked at</h3><p>When his best attention was available, what work occupied those hours, and how the working day ended. We examined the fit between the work and the state he brought to it.</p></div><div><h3>The judgment</h3><p>Increasing effort was one possible response. A more useful hypothesis to test was whether his best capacity was reaching his highest-value work.</p></div><div><h3>What changed</h3><p>We matched work to state, protected his best hours for higher-value work, moved lower-value demands, planned recovery, and established a shutdown ritual.</p></div><div><h3>What he reported</h3><p>Nearly 200% of plan after three months and his strongest Q1 in five years. The work also emphasized staying engaged at home.</p></div><div><h3>What this establishes</h3><p>A client-reported outcome during an earlier engagement. There is no controlled comparison or independent audit, so this does not isolate the effect of advisory or predict a 30-day result.</p></div></div></article></section>
<section class="wrap evidence-voices"><div class="section-intro"><p class="eyebrow">In their words</p><h2>The value from<br><span>the other side of the table.</span></h2></div><div class="voice-grid"><figure><blockquote>“The strongest testimonial I can give you is the five digit sum I pay to have six months of private advisory calls with Marcus. I feel like I am getting every penny’s worth.”</blockquote><figcaption><strong>Ethan Evans</strong><span>Former Amazon VP · Private advisory</span></figcaption></figure><figure><blockquote>“Marcus helped me understand what I needed to perform better, stay healthier, and be more durable.”</blockquote><figcaption><strong>Ryan McMahon</strong><span>MLB All-Star · Professional baseball work</span></figcaption></figure><figure><blockquote>“He could go vertically deep and horizontally in recommending operationally, physically, and psychologically.”</blockquote><figcaption><strong>Ted Tanner</strong><span>Review of work through FRC</span><a class="text-link" href="https://www.tedtanner.org/review-flow-research-collective/">Read the public review</a></figcaption></figure></div><p class="small muted">Selected accounts from earlier work across different settings. Roles identify the individuals; company names do not imply corporate endorsements.</p></section>
<section class="deliverable-section" id="deliverable"><div class="wrap deliverable-grid"><div><p class="eyebrow">A tangible output</p><h2>Your Performance Map.</h2><p>A concise record of the result, the working explanation, the change, and what the evidence says next.</p><p class="small muted">This example is reconstructed from the case above using the structure used in engagements. It is not an original client document; identifying and operational details are omitted.</p>{button('Explore the Intensive','/advisory/','text-link')}</div><article class="performance-map"><header><span>VYRTŪOSITI</span><span>Example · Anonymized</span></header><h3>Commercial performance<br>& room for life.</h3><dl><div><dt>North star</dt><dd>More repeatable commercial performance, with a deliberate end to the working day.</dd></div><div><dt>Working constraint</dt><dd>Best capacity may be reaching lower-value work.</dd></div><div><dt>Intervention</dt><dd>Protect high-value work in the best hours. Plan recovery and a shutdown ritual.</dd></div><div><dt>Evidence record</dt><dd>Client reported nearly 200% of plan after three months. Causal contribution remains unisolated.</dd></div><div><dt>Next review</dt><dd>Which changes held under real demand? What should stay, change, or stop?</dd></div></dl></article></div></section>
<section class="closing-cta wrap"><p class="eyebrow">Bring your own context</p><h2>What result is worth<br><span>getting right?</span></h2>{button()}</section>'''
page('evidence/index.html','Evidence | Marcus Lefton & VYRTŪOSITI','A detailed client case, selected testimonials, and an example Performance Map. Examine the work behind Marcus Lefton’s private performance advisory.',evidence,'evidence')

publication=f'''<section class="publication-hero wrap"><p class="eyebrow">A Sunday letter by Marcus Lefton</p><h1>Mastery<br><span>in Motion.</span></h1><div class="publication-intro"><p class="lead">See the pattern.<br>Make one useful change.</p><div><p>One idea each Sunday, drawn from professional sport, applied performance, and private advisory. A sharper way to see how you work—and something practical to test.</p>{newsletter_form('join')}</div></div></section>
<section class="paper-section"><div class="wrap"><div class="section-intro horizontal"><div><p class="eyebrow">Start here</p><h2>From the field.</h2></div><p>Read a note. Try an idea.<br>Keep what earns its place.</p></div><div class="reading-list"><a href="/mastery-in-motion/the-cost-of-compensation/"><span>Field note · 4 min</span><h3>High performers can make<br>bad systems look healthy.</h3><p>What your ability to keep delivering can conceal.</p><span class="text-link">Read the note</span></a><a href="/MED/"><span>Field guide</span><h3>The minimum<br>effective dose.</h3><p>A practical resource for reviewing the inputs behind your performance.</p><span class="text-link">Open the guide</span></a></div></div></section>
<section class="wrap publication-about"><p class="eyebrow">The person behind the letter</p><h2>Written from<br><span>work with real stakes.</span></h2><p>I’m Marcus Lefton. I’ve worked in physical performance with the Colorado Rockies, coached and led programs at Flow Research Collective, and advise founders and high-stakes operators through VYRTŪOSITI.</p><p>The letter shares the observations, questions, and small experiments that help people see their next move more clearly.</p>{button('About the advisory','/advisory/','text-link')}</section>'''
page('mastery-in-motion/index.html','Mastery in Motion | Marcus Lefton’s Sunday Letter','One useful idea each Sunday from professional sport, applied performance, and private advisory. Read Marcus Lefton’s field notes and join Mastery in Motion.',publication,'publication')

article=f'''<article class="article wrap"><header><a class="text-link" href="/mastery-in-motion/">Mastery in Motion</a><p class="eyebrow">Field note · Marcus Lefton</p><h1>High performers can make bad systems look healthy.</h1><p class="lead">Your ability to keep delivering can conceal the cost of the way you work.</p></header><div class="article-body"><p>The work gets done. The client stays happy. The decision gets made. From the outside, the system appears to function.</p><p>Look more closely at where the effort lands. You might be the person catching the dropped handoff, making the decision someone else owns, or finishing your most important work after everyone else has stopped.</p><h2>Start with what keeps reaching you.</h2><p>Pick one recurring interruption from the last week. A request for approval. A deliverable that needs rescuing. A question the team cannot answer without you.</p><p>Ask what would need to be true for the next occurrence to move forward without your involvement.</p><ul><li>Does someone have clear ownership?</li><li>Do they have the capability and an example of the standard?</li><li>Is there a decision rule they can use?</li><li>Is the escalation threshold clear?</li></ul><p>Different answers point to different work. A missing skill needs practice. Unclear ownership needs a decision. A vague standard needs an example. More focus from you may leave each of those conditions unchanged.</p><h2>Run a small test.</h2><p>Choose one recurring decision. Agree who owns it, what good looks like, and when it should return to you. Try that arrangement for a week.</p><p>Watch both sides: how often you are interrupted, and whether the quality of the decision holds. Time recovered without a dependable result is an incomplete improvement.</p><h2>Check the wider system.</h2><p>Reclaimed time also needs a purpose. Put it toward the result that matters, or toward recovery that makes your best work more available. Otherwise, the calendar can refill before anything meaningfully changes.</p><p>That is the work of performance architecture: start with the result, find what is limiting it, change the system, and test it against reality.</p><aside class="article-question"><span class="small-label">A question for your week</span><p>What is one thing someone else technically owns that you still end up touching?</p></aside><p>If there is a consequential result you want to produce, and your current approach is costing too much, <a href="/advisory/">explore the 30-day Intensive</a>.</p></div><div class="article-subscribe"><h2>One useful idea.<br>Every Sunday.</h2>{newsletter_form('article-join')}</div></article>'''
page('mastery-in-motion/the-cost-of-compensation/index.html','High performers can make bad systems look healthy | Mastery in Motion','A field note on recurring decisions, hidden dependence, and testing a change that protects both capacity and the quality of the result.',article,'publication')

page('contact/index.html','Contact Marcus Lefton | VYRTŪOSITI','Contact Marcus Lefton for private advisory and other enquiries.',f'<section class="page-hero wrap contact"><p class="eyebrow">Contact</p><h1>Start with<br><span>what matters.</span></h1><p class="lead">For private advisory, tell me the result you are working toward and what is getting in the way.</p>{button("Apply for the Intensive","/advisory/#apply")}<div class="contact-detail"><h2>Other enquiries</h2><a class="text-link" href="mailto:marcus@marcuslefton.com">marcus@marcuslefton.com</a><p>Based in Arizona. Working with clients remotely.</p></div></section>')
page('thankyou/index.html','Check your inbox | Mastery in Motion','Your subscription request has been received. Check your inbox for the next step.',f'<section class="confirmation wrap"><p class="eyebrow">Mastery in Motion</p><h1>Check your inbox.</h1><p class="lead">If you have just subscribed, look for an email from Marcus and confirm your address if prompted. Check spam or promotions if it has not arrived.</p><p>Already subscribed? You’ll continue receiving the Sunday letter.</p><div class="actions">{button("Read a field note","/mastery-in-motion/the-cost-of-compensation/")}{button("Return home","/","text-link")}</div><p class="small">Need help? <a href="mailto:marcus@marcuslefton.com">Email Marcus</a>.</p></section>',noindex=True)
page('application-received/index.html','Application received | Marcus Lefton','Your application has been received. Marcus will review it and reply by email.',f'<section class="confirmation wrap"><p class="eyebrow">Private advisory</p><h1>Thank you<br><span>for the context.</span></h1><p class="lead">If you have just submitted the application, it has been received. I’ll review it and reply by email about fit and next steps.</p><p>No payment has been taken. If the fit looks promising, we’ll arrange a complimentary 15-minute conversation.</p>{button("Explore the evidence","/evidence/")}<p class="small">Something to add? <a href="mailto:marcus@marcuslefton.com">marcus@marcuslefton.com</a>.</p></section>',noindex=True)
page('404.html','Page not found | Marcus Lefton','Find private advisory, evidence, and Mastery in Motion.',f'<section class="confirmation wrap"><p class="eyebrow">Page not found</p><h1>Let’s get you<br><span>to the right place.</span></h1><div class="actions">{button("Return home","/")}{button("Private advisory","/advisory/","text-link")}</div></section>',noindex=True)

# Preserve the existing legal wording; replace presentation and shared navigation only.
for name,title in [('privacy','Privacy Policy'),('terms-of-service','Terms of Service')]:
    source_path=ROOT/'tools'/f'{name}.source.html'
    if not source_path.exists():
        source_path.write_text((ROOT/name/'index.html').read_text())
    text=source_path.read_text()
    body=text.split('<div class="policy-container">',1)[1].split('<div class="footer-block',1)[0]
    body=re.sub(r'<div class="brand-mark[^>]*>.*?</div>','',body,flags=re.S)
    body=re.sub(r'\sstyle="[^"]*"','',body)
    body=body.replace('fade-up','')
    body=re.sub(r'(?m)^\s+$','',body)
    page(name+'/index.html',title+' | VYRTŪOSITI',title+' for VYRTŪOSITI LLC.',f'<article class="legal wrap">{body}</article>')

routes=['/','/advisory/','/evidence/','/mastery-in-motion/','/mastery-in-motion/the-cost-of-compensation/','/contact/','/privacy/','/terms-of-service/','/MED/']
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{ORIGIN}{r}</loc></url>' for r in routes)+'</urlset>')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /tools/\nDisallow: /docs/\nDisallow: /draft/\nSitemap: '+ORIGIN+'/sitemap.xml\n')
print('Generated primary, article, legal, contact, and confirmation pages.')
