const {test} = require('node:test');
const assert = require('node:assert/strict');
const {handlerFor} = require('../netlify/lib/forms');
const newsletter = handlerFor('newsletter');
const application = handlerFor('application');
const event = data => ({httpMethod:'POST',headers:{origin:'https://www.marcuslefton.com','content-type':'application/json'},body:JSON.stringify(data)});
const complete = {email:'qa@example.com',first_name:'Website QA',role_company:'Test',current_issue:'Test submission',readiness:'Yes',source:'advisory | linkedin / featured'};
test('form transport, routing, validation, and truthful confirmation', async () => {
  process.env.KIT_API_KEY = 'test-fixture-key';
  let captured;
  global.fetch = async (url,options) => { captured={url,payload:JSON.parse(options.body)};return {ok:true,status:200,json:async()=>({subscription:{id:123}})}; };
  let res=await newsletter(event({email:' QA@example.com ',source:'mastery_in_motion | linkedin'}));
  assert.equal(res.statusCode,200);assert.equal(JSON.parse(res.body).ok,true);assert.match(captured.url,/9270901/);assert.equal(captured.payload.email,'qa@example.com');assert.equal(captured.payload.fields.opt_in_source,'mastery_in_motion | linkedin');
  res=await application(event(complete));
  assert.equal(res.statusCode,200);assert.match(captured.url,/9586922/);assert.equal(captured.payload.fields.bottleneck_current_issue,'Test submission');assert.equal(captured.payload.first_name,'Website QA');assert.equal(captured.payload.fields.bottleneck_audit_readiness,'Yes');
  res=await application({...event(complete),headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(complete).toString()});
  assert.equal(res.statusCode,303);assert.equal(res.headers.Location,'/application-received/');
  res=await newsletter({...event({email:'qa@example.com'}),headers:{'content-type':'application/x-www-form-urlencoded'},body:'email=qa%40example.com'});
  assert.equal(res.statusCode,303);assert.equal(res.headers.Location,'/thankyou/');
  assert.equal((await newsletter(event({email:'broken'}))).statusCode,400);
  assert.equal((await newsletter(event(null))).statusCode,400);
  assert.equal((await newsletter({...event({}),body:'{'})).statusCode,400);
  assert.equal((await application(event({...complete,current_issue:''}))).statusCode,400);
  assert.equal((await application(event({...complete,current_issue:'x'.repeat(3001)}))).statusCode,400);
  assert.equal((await application(event({...complete,linkedin_website:'javascript:alert(1)'}))).statusCode,400);
  assert.equal((await newsletter({...event({}),httpMethod:'GET'})).statusCode,405);
  assert.equal((await newsletter({...event({email:'qa@example.com'}),headers:{origin:'https://unrelated.example'}})).statusCode,403);
  captured=null;assert.equal((await newsletter(event({website:'bot',email:'qa@example.com'}))).statusCode,200);assert.equal(captured,null);
  global.fetch=async()=>({ok:false,status:422,json:async()=>({error:'Rejected'})});
  res=await application(event(complete));assert.equal(res.statusCode,502);assert.equal(JSON.parse(res.body).ok,undefined);
  global.fetch=async()=>({ok:true,status:200,json:async()=>({})});
  assert.equal((await newsletter(event({email:'qa@example.com'}))).statusCode,502);
  global.fetch=async()=>{throw new Error('network failure')};
  assert.equal((await newsletter(event({email:'qa@example.com'}))).statusCode,502);
  delete process.env.KIT_API_KEY;
  assert.equal((await newsletter(event({email:'qa@example.com'}))).statusCode,503);
});
